# Generated by Django 4.2.1 on 2023-06-05 17:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keypay',
            fields=[
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.station')),
                ('metodos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64, null=True), null=True, size=5)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['contador']},
        ),
    ]
